package aQute.poma.visa;

import java.util.*;

import com.vaadin.annotations.*;
import com.vaadin.ui.*;

public class VisaForm extends CustomComponent {
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private NativeSelect year;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private NativeSelect month;
	@AutoGenerated
	private TextField CCV;
	@AutoGenerated
	private Label lCCV;
	@AutoGenerated
	private Label lCCExpDate;
	@AutoGenerated
	private TextField ccName;
	@AutoGenerated
	private Label lCCName;
	@AutoGenerated
	private TextField ccNumber;
	@AutoGenerated
	private Label lCCNumber;


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public VisaForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		for ( int i = 1; i<=12; i++ ) {
			month.addItem(i+"");
		}
		month.select("1");
		int start = Calendar.getInstance().get(Calendar.YEAR);
		for ( int i = start; i<=start+10; i++ ) {
			this.year.addItem(i+"");
		}
		this.year.select(start+"");		
		
	}


	public String getCCNumber() {
		return (String) ccNumber.getValue();
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("460px");
		mainLayout.setHeight("140px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("460px");
		setHeight("140px");
		
		// lCCNumber
		lCCNumber = new Label();
		lCCNumber.setImmediate(false);
		lCCNumber.setWidth("-1px");
		lCCNumber.setHeight("-1px");
		lCCNumber.setValue("Credit Card Nr");
		mainLayout.addComponent(lCCNumber, "top:20.0px;left:20.0px;");
		
		// ccNumber
		ccNumber = new TextField();
		ccNumber.setImmediate(false);
		ccNumber.setWidth("320px");
		ccNumber.setHeight("-1px");
		ccNumber.setSecret(false);
		mainLayout.addComponent(ccNumber, "top:20.0px;left:120.0px;");
		
		// lCCName
		lCCName = new Label();
		lCCName.setImmediate(false);
		lCCName.setWidth("-1px");
		lCCName.setHeight("-1px");
		lCCName.setValue("Name on Card");
		mainLayout.addComponent(lCCName, "top:62.0px;left:20.0px;");
		
		// ccName
		ccName = new TextField();
		ccName.setImmediate(false);
		ccName.setWidth("320px");
		ccName.setHeight("-1px");
		ccName.setSecret(false);
		mainLayout.addComponent(ccName, "top:60.0px;left:120.0px;");
		
		// lCCExpDate
		lCCExpDate = new Label();
		lCCExpDate.setImmediate(false);
		lCCExpDate.setWidth("-1px");
		lCCExpDate.setHeight("-1px");
		lCCExpDate.setValue("Exp. Date");
		mainLayout.addComponent(lCCExpDate, "top:101.0px;left:200.0px;");
		
		// lCCV
		lCCV = new Label();
		lCCV.setImmediate(false);
		lCCV.setWidth("-1px");
		lCCV.setHeight("-1px");
		lCCV.setValue("CCV");
		mainLayout.addComponent(lCCV, "top:100.0px;left:20.0px;");
		
		// CCV
		CCV = new TextField();
		CCV.setImmediate(false);
		CCV.setWidth("57px");
		CCV.setHeight("-1px");
		CCV.setSecret(false);
		mainLayout.addComponent(CCV, "top:100.0px;left:120.0px;");
		
		// month
		month = new NativeSelect();
		month.setImmediate(false);
		month.setWidth("-1px");
		month.setHeight("-1px");
		mainLayout.addComponent(month, "top:98.0px;left:271.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("/");
		mainLayout.addComponent(label_1, "top:100.0px;left:357.0px;");
		
		// year
		year = new NativeSelect();
		year.setImmediate(false);
		year.setWidth("60px");
		year.setHeight("-1px");
		mainLayout.addComponent(year, "top:98.0px;left:380.0px;");
		
		return mainLayout;
	}

}
